"""
Django settings for devsec_demo project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG') == 'True'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # User Authentication Service
    'mupenz_fulgence',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'devsec_demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # RBAC: injects user_role, is_instructor, is_staff_member, is_admin
                'mupenz_fulgence.context_processors.user_roles',
            ],
        },
    },
]

WSGI_APPLICATION = 'devsec_demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ── Media files (user uploads) ─────────────────────────────────────────────
# MEDIA_ROOT is the filesystem directory where uploaded files are stored.
# MEDIA_URL is the URL prefix used to serve PUBLIC media files (avatars).
#
# SECURITY NOTES:
#   • Documents are stored under MEDIA_ROOT/documents/ but are NOT served via
#     MEDIA_URL.  They must be accessed ONLY via DocumentServeView, which
#     enforces per-user ownership checks.
#   • In production, configure your web server (Nginx / Apache) to serve
#     MEDIA_ROOT/avatars/ directly but deny direct access to
#     MEDIA_ROOT/documents/ — all document requests should proxy through Django.
#   • Never set MEDIA_ROOT inside a directory served as STATIC_ROOT.
MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ── Upload size limits ─────────────────────────────────────────────────────
# Django's in-memory upload threshold — files larger than this are written to
# a temporary file on disk instead of being held in RAM.  This is NOT a
# security limit; the per-type size limits are enforced in validators.py.
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024   # 2 MB in-memory threshold
# Cap the total size of a single multipart POST body.  This prevents a
# client from sending an unbounded request body before Django reads it.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB max request body

# ── Authentication routing ─────────────────────────────────────────────────
# Where to send users after a successful login / logout,
# and where LoginRequiredMixin redirects unauthenticated requests.
LOGIN_REDIRECT_URL = '/auth/'
LOGOUT_REDIRECT_URL = '/auth/login/'
LOGIN_URL = '/auth/login/'

# ── Cache ──────────────────────────────────────────────────────────────────
# Development default: in-process LocMemCache (no external server needed).
# For production set DJANGO_CACHE_BACKEND (e.g. django_redis.cache.RedisCache)
# and DJANGO_CACHE_LOCATION (e.g. redis://127.0.0.1:6379/1).
# Multi-process or multi-server deployments MUST use a shared backend
# (Redis / Memcached) so that lockout state is visible across all workers.
CACHES = {
    'default': {
        'BACKEND': os.environ.get(
            'DJANGO_CACHE_BACKEND',
            'django.core.cache.backends.locmem.LocMemCache',
        ),
        'LOCATION': os.environ.get('DJANGO_CACHE_LOCATION', 'mf-auth-cache'),
    }
}

# ── Login brute-force protection ──────────────────────────────────────────
# Maximum consecutive failed login attempts before an account is locked.
LOGIN_MAX_ATTEMPTS = int(os.environ.get('LOGIN_MAX_ATTEMPTS', 5))
# Seconds the account stays locked after reaching the threshold.
LOGIN_LOCKOUT_DURATION = int(os.environ.get('LOGIN_LOCKOUT_DURATION', 900))   # 15 min
# Rolling window (seconds) in which failures are counted.
LOGIN_ATTEMPT_WINDOW = int(os.environ.get('LOGIN_ATTEMPT_WINDOW', 900))       # 15 min

# ── Email ──────────────────────────────────────────────────────────────────
# Development default: print emails to the console (no SMTP server needed).
# In production set DJANGO_EMAIL_BACKEND to an SMTP or transactional backend
# and supply DJANGO_DEFAULT_FROM_EMAIL with a deliverable address.
EMAIL_BACKEND = os.environ.get(
    'DJANGO_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_DEFAULT_FROM_EMAIL', 'noreply@mf-auth.local')

# ── Password reset token validity ─────────────────────────────────────────
# Number of seconds a password-reset link remains valid (default Django: 3 days).
# Reducing to 1 hour limits the window during which an intercepted link is
# exploitable.  The token is also single-use — it becomes invalid the moment
# the password is changed (because the HMAC input includes the password hash).
PASSWORD_RESET_TIMEOUT = 3600  # 1 hour
